<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<title>F023-THHC Employee Data Form| @yield('title')</title>

<style>

	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
.xl6316102
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Montserrat;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6416102
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Montserrat;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:top;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6516102
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Montserrat SemiBold";
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6616102
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Montserrat;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6716102
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Montserrat;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:top;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6816102
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Montserrat;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:top;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6916102
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Montserrat;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:top;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}

</style>
@yield('styles')

</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="F023-THHC Employee Data Form_16102" align=center
x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=630 class=xl6316102
 style='border-collapse:collapse;table-layout:fixed;width:470pt'>
 <col class=xl6316102 width=63 span=10 style='width:47pt'>
 <tr height=88 style='mso-height-source:userset;height:66.0pt'>
  <td colspan=9 height=88 width=567 style='height:66.0pt;width:423pt'
  align=left valign=top><span style='mso-ignore:vglayout;
  position:absolute;z-index:1;margin-left:9px;margin-top:25px;width:158px;
  height:50px'><img width=158 height=50
  src="F023-THHC%20Employee%20Data%20Form.files/F023-THHC%20Employee%20Data%20Form_16102_image002.png"
  v:shapes="Picture_x0020_1"></span><span style='mso-ignore:vglayout2'>
  <table cellpadding=0 cellspacing=0>
   <tr>
    <td colspan=9 height=88 class=xl6516102 width=567 style='height:66.0pt;
    width:423pt'>Employee Data Form</td>
   </tr>
  </table>
  </span></td>
  <td class=xl6316102 width=63 style='width:47pt'></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td colspan=9 height=24 class=xl6716102 style='height:18.0pt'>Employee Name:</td>
  <td class=xl6316102></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td colspan=3 height=24 class=xl6716102 style='height:18.0pt'>Blood
  group:<span style='mso-spacerun:yes'></span></td>
  <td colspan=2 class=xl6716102 style='border-left:none'>Gender:</td>
  <td colspan=2 class=xl6716102 style='border-left:none'>Nationality:</td>
  <td colspan=2 class=xl6716102 style='border-left:none'>ID #:</td>
  <td class=xl6316102></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td colspan=3 height=24 class=xl6716102 style='height:18.0pt'>Marital
  Status:<span style='mso-spacerun:yes'></span></td>
  <td colspan=3 class=xl6716102 style='border-left:none'>Land Line #:</td>
  <td colspan=3 class=xl6716102 style='border-left:none'>Mobile #:</td>
  <td class=xl6316102></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td colspan=9 height=24 class=xl6716102 style='height:18.0pt'>Email:</td>
  <td class=xl6316102></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td colspan=9 height=24 class=xl6716102 style='height:18.0pt'>Level of
  Education:</td>
  <td class=xl6316102></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td colspan=9 height=24 class=xl6716102 style='height:18.0pt'>Place of
  Residence in KSA:</td>
  <td class=xl6316102></td>
 </tr>
 <tr height=72 style='mso-height-source:userset;height:54.45pt'>
  <td colspan=9 height=72 class=xl6816102 width=567 style='height:54.45pt;
  width:423pt'>Place of Residence outside KSA:<br>
    <br>
    Land Line #:<span
  style='mso-spacerun:yes'>
  </span>Mobile #:<span style='mso-spacerun:yes'></span></td>
  <td class=xl6316102></td>
 </tr>
 <tr height=89 style='mso-height-source:userset;height:67.05pt'>
  <td colspan=9 height=89 class=xl6816102 width=567 style='height:67.05pt;
  width:423pt'>Person we can contact:<br>
    Name :<span
  style='mso-spacerun:yes'>
  </span>Relation:<span
  style='mso-spacerun:yes'></span>contact
  #:<br>
    Name :<span
  style='mso-spacerun:yes'>
  </span>Relation:<span
  style='mso-spacerun:yes'> </span>contact
  #:<br>
    Name :<span style='mso-spacerun:yes'>
  </span>Relation:<span
  style='mso-spacerun:yes'> </span>contact #:</td>
  <td class=xl6316102></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td colspan=9 height=24 class=xl6716102 style='height:18.0pt'>Number of
  Family (<span style='mso-spacerun:yes'> </span>)<span
  style='mso-spacerun:yes'></span></td>
  <td class=xl6316102></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td colspan=3 height=24 class=xl6416102 style='height:18.0pt'>Name</td>
  <td colspan=2 class=xl6416102 style='border-left:none'>Relation</td>
  <td colspan=2 class=xl6416102 style='border-left:none'>Work Place</td>
  <td colspan=2 class=xl6416102 style='border-left:none'>DOB</td>
  <td class=xl6316102></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td colspan=3 height=24 class=xl6416102 style='height:18.0pt'>&nbsp;</td>
  <td colspan=2 class=xl6416102 style='border-left:none'>&nbsp;</td>
  <td colspan=2 class=xl6416102 style='border-left:none'>&nbsp;</td>
  <td colspan=2 class=xl6416102 style='border-left:none'>&nbsp;</td>
  <td class=xl6316102></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td colspan=3 height=24 class=xl6416102 style='height:18.0pt'>&nbsp;</td>
  <td colspan=2 class=xl6416102 style='border-left:none'>&nbsp;</td>
  <td colspan=2 class=xl6416102 style='border-left:none'>&nbsp;</td>
  <td colspan=2 class=xl6416102 style='border-left:none'>&nbsp;</td>
  <td class=xl6316102></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td colspan=3 height=24 class=xl6416102 style='height:18.0pt'>&nbsp;</td>
  <td colspan=2 class=xl6416102 style='border-left:none'>&nbsp;</td>
  <td colspan=2 class=xl6416102 style='border-left:none'>&nbsp;</td>
  <td colspan=2 class=xl6416102 style='border-left:none'>&nbsp;</td>
  <td class=xl6316102></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td colspan=3 height=24 class=xl6416102 style='height:18.0pt'>&nbsp;</td>
  <td colspan=2 class=xl6416102 style='border-left:none'>&nbsp;</td>
  <td colspan=2 class=xl6416102 style='border-left:none'>&nbsp;</td>
  <td colspan=2 class=xl6416102 style='border-left:none'>&nbsp;</td>
  <td class=xl6316102></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td colspan=3 height=24 class=xl6416102 style='height:18.0pt'>&nbsp;</td>
  <td colspan=2 class=xl6416102 style='border-left:none'>&nbsp;</td>
  <td colspan=2 class=xl6416102 style='border-left:none'>&nbsp;</td>
  <td colspan=2 class=xl6416102 style='border-left:none'>&nbsp;</td>
  <td class=xl6316102></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td colspan=3 height=24 class=xl6416102 style='height:18.0pt'>&nbsp;</td>
  <td colspan=2 class=xl6416102 style='border-left:none'>&nbsp;</td>
  <td colspan=2 class=xl6416102 style='border-left:none'>&nbsp;</td>
  <td colspan=2 class=xl6416102 style='border-left:none'>&nbsp;</td>
  <td class=xl6316102></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td colspan=3 height=24 class=xl6416102 style='height:18.0pt'>&nbsp;</td>
  <td colspan=2 class=xl6416102 style='border-left:none'>&nbsp;</td>
  <td colspan=2 class=xl6416102 style='border-left:none'>&nbsp;</td>
  <td colspan=2 class=xl6416102 style='border-left:none'>&nbsp;</td>
  <td class=xl6316102></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td colspan=3 height=24 class=xl6416102 style='height:18.0pt'>&nbsp;</td>
  <td colspan=2 class=xl6416102 style='border-left:none'>&nbsp;</td>
  <td colspan=2 class=xl6416102 style='border-left:none'>&nbsp;</td>
  <td colspan=2 class=xl6416102 style='border-left:none'>&nbsp;</td>
  <td class=xl6316102></td>
 </tr>
 <tr height=75 style='mso-height-source:userset;height:56.55pt'>
  <td colspan=9 height=75 class=xl6816102 width=567 style='height:56.55pt;
  width:423pt'>If the employee is still pursusing his education:<br>
    Level of
  Education:_______________________________________________________________<br>
    The name of
  institution:_____________________________________________________________</td>
  <td class=xl6316102></td>
 </tr>
 <tr height=239 style='mso-height-source:userset;height:179.55pt'>
  <td colspan=9 height=239 class=xl6816102 width=567 style='height:179.55pt;
  width:423pt'>Approved sign that all data provided is true and I pledge in the
  event of change of any of the above information notify the THHC Manager/Human
  Resources immediately for modifying them,In case it turns out there has been
  the provision of inaccurate data the management has right to apply any
  sanction it deems appropriate.<br>
    <br>
    Employee Name:
  ____________________________________________________________________<br>
    Signature:
  ___________________________________________________________________________<br>
    ID Number:____________________________________________ Date:
  _______________________<br>
    </td>
  <td class=xl6316102></td>
 </tr>
 <tr height=18 style='height:13.8pt'>
  <td colspan=9 height=18 class=xl6916102 style='height:13.8pt'></td>
  <td class=xl6316102></td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=63 style='width:47pt'></td>
  <td width=63 style='width:47pt'></td>
  <td width=63 style='width:47pt'></td>
  <td width=63 style='width:47pt'></td>
  <td width=63 style='width:47pt'></td>
  <td width=63 style='width:47pt'></td>
  <td width=63 style='width:47pt'></td>
  <td width=63 style='width:47pt'></td>
  <td width=63 style='width:47pt'></td>
  <td width=63 style='width:47pt'></td>
 </tr>

</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>

</html>
